### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by storytime** [enonic/starter-vanilla#2]
Im not sure that is really a problem, but,

I've installed **enonic-xp-6.3.1** and then followed the [MyApp ](http://xp.readthedocs.org/en/stable/tutorials/my-first-app/hello-world-site.html)tutorial, but this step is not worked. 

I've checked  **gradle.properties** the value was **xpVersion = 6.4** , but I've changed it to **xpVersion = 6.3.1** and  and only then code from tutorial stars working, 

Please add this note to the tutorial, because for newbie this issue is not very oblivious.

**Comment by sigdestad** [comment]
Hi!
Vanilla starter will only work With 6.4+ as it is using new features, 6.4 is the new stable - please go to our forum for questions. We'll clearify our docs on this point!

Vennlig hilsen/Best regards 

Thomas Sigdestad
CTO & Co-Founder

https://enonic.com - A web operating system for your sites and applications

**Comment by Michael-Lazell** [comment]
Vanilla-starter has a new folder structure for XP version 6.4, but none of the folders that have moved are used in the tutorial so I think it should work ok on 6.3. If you are using 6.3 then you should use the tutorial in the 6.3 documentation which has starter-base instead of starter-vanilla. But you should use 6.4 now that it's out. [](http://repo.enonic.com/public/com/enonic/xp/distro/6.4.0/distro-6.4.0.zip)
